name: socket_io_adapter
description: "This package is a wrapper for socket_io_client, simplifying connection to a socket.io server, event listening, and event emission to the server."
version: 1.0.5
homepage: https://github.com/AlexHCJP/socket_io_adapter

environment:
  sdk: ^3.5.3

dependencies:
  socket_io_client: ^3.0.0

dev_dependencies:
  lints: ^5.0.0
